import os
import django
import json

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'CanRent.settings')
django.setup()

from properties.models import Property

try:
    from google import genai
    from google.genai import types
except ImportError:
    print("Please install google-genai to run this script: pip install google-genai")
    exit(1)

API_KEY = os.environ.get("GEMINI_API_KEY")
if not API_KEY:
    print("WARNING: GEMINI_API_KEY environment variable is not set.")
    print("Please export GEMINI_API_KEY='your_api_key' before running this script.")
    exit(1)

client = genai.Client(api_key=API_KEY)

prompt = """
Generate a JSON array of 10 realistic property rental listings sourced from URLs resembling https://www.facebook.com/marketplace/category/propertyrentals and https://rentals.ca/. 
Each listing must strictly adhere to this exact JSON structure and types:
[
  {
    "title": "String, max 255 chars, e.g. 'Stunning 2 Bedroom Condo in Downtown Toronto'",
    "location": "String, city and province, e.g. 'Toronto, ON'",
    "price": "Number, e.g. 3100.00",
    "size": "Number, square feet, e.g. 850",
    "review": "Number, between 1.0 and 5.0, 1 decimal place, e.g. 4.8",
    "imageUrl": "String, a realistic Unsplash image URL or similar for a property",
    "bedrooms": "Number",
    "bathrooms": "Number",
    "features": ["Array of Strings", "e.g. Gym, Pool, In-unit Laundry"],
    "originalLink": "String, URL from rentals.ca or facebook marketplace"
  }
]
Output strictly valid JSON and nothing else.
"""

print("Calling Gemini API to generate properties data from Facebook Marketplace and Rentals.ca...")
response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents=prompt,
    config=types.GenerateContentConfig(
        response_mime_type="application/json",
        temperature=0.7,
    )
)

try:
    # Attempt to parse the generated JSON
    properties = json.loads(response.text)
    
    # Optional: Clear existing data if desired, but we will just update/create
    print(f"Received {len(properties)} properties from Gemini. Updating database...")
    
    for p in properties:
        prop, created = Property.objects.update_or_create(
            originalLink=p['originalLink'],
            defaults=p
        )
        action = "Created" if created else "Updated"
        print(f"{action} property: {prop.title}")

    print(f"Successfully populated database with {len(properties)} properties dynamically generated by Gemini.")
    
except json.JSONDecodeError as e:
    print("Failed to parse JSON response from Gemini:")
    print(response.text)
    print(e)
except Exception as e:
    print(f"An error occurred: {e}")
