# Generated by Django 6.0.3 on 2026-03-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.IntegerField()),
                ('review', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imageUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('features', models.JSONField(default=list)),
                ('original_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
