# Generated by Django 6.0.3 on 2026-03-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='original_link',
            new_name='originalLink',
        ),
    ]
